/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaPanelApusDialog;

import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import vistaPanelApus.panelApus;

/**
 *
 * @author personal1
 */
public class dialogRendimiento extends javax.swing.JInternalFrame {

    /**
     * Creates new form dialogEquipo
     */
    private Character kpress;
    public static Object [] fila;
    
    
    public dialogRendimiento() {
        initComponents();     
        setTitle("Cálculo de rendimiento APUS");
        jTextField1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnClosed = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Total tarifa de equipo y mano de obra: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, 230, -1));

        jTextField1.setText("a");
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 42, 79, -1));

        btnClosed.setText("X");
        btnClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosedActionPerformed(evt);
            }
        });
        jPanel1.add(btnClosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        jLabel3.setText("Mano de obra sueldo");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 73, 209, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cantidad", "Sueldo", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tableKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 93, -1, 92));

        jLabel4.setText("SubTotal 1");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 200, 60, -1));

        jTextField2.setText("b = tblTOT");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 191, 106, -1));

        jLabel5.setText("Adicional");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, 60, -1));

        jLabel6.setText("Variable");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 220, 70, -1));

        jTextField3.setText("6");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 216, 106, -1));

        jTextField4.setText("b / adicional");
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(358, 242, 106, -1));

        jLabel1.setText("Rendimiento");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, -1));

        jTextField5.setText("total / b");
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 106, -1));

        jLabel7.setText("%");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, -1, -1));

        jTextField6.setText("1.55");
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 106, -1));

        jTextField7.setText("jTextField7");
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 325, 106, -1));

        jLabel8.setText("Rendimiento + %");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, -1, -1));

        jLabel9.setText("Subtotal 2");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jTextField8.setText("jTextField8");
        jTextField8.setPreferredSize(new java.awt.Dimension(62, 20));
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, 100, -1));

        jButton1.setText("Calcular SubTotal 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosedActionPerformed
        this.dispose();
        panelApus.activoDlgRendimiento = false;
    }//GEN-LAST:event_btnClosedActionPerformed

    private void tableKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableKeyPressed
        kpress = evt.getKeyChar();
        if (kpress == KeyEvent.VK_ENTER) {
            calTotTbl("keyPress");
        }
    }//GEN-LAST:event_tableKeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        calTotTbl("");
        
        calSubTot1();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
         kpress = evt.getKeyChar();
        if (kpress == KeyEvent.VK_ENTER) {
            String val = jTextField3.getText();
            if(!val.equals("")){
                double adicio = Double.parseDouble(val);
                double subTot1 = Double.parseDouble(jTextField2.getText());
                // llenamos subTotal 2   solo 2 decimales
                 jTextField4.setText(String.valueOf((double)Math.round((subTot1 / adicio ) * 100d) / 100d));   
            }
            
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogRendimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogRendimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogRendimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogRendimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dialogRendimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClosed;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    public static javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables


    // llenar tabla con cantidad de mano de obra
    public static void setTableCant(List<String> list){
        limpiarTabla();
        DefaultTableModel modelo=(DefaultTableModel) table.getModel(); 
        Object [] fila=new Object[3]; 
        //Sección 3
        for(int i = 0; i<list.size();++i){
            fila[0]=list.get(i); // cantidad
            fila[1]=""; // 
            fila[2]=""; // 
            //Sección 4
            modelo.addRow(fila);
        }
        //Sección 5
        table.setModel(modelo); 

    }
    
    // llenar tabla con cantidad de mano de obra modo update cantidad
    public static void setTableCantUpdate(List<String> list){        
        int size = table.getRowCount();
        for(int i = 0; i<list.size();++i){
            if(i<size){
                table.setValueAt(list.get(i), i, 0); // pongo el valor     
            }else{
                DefaultTableModel modelo=(DefaultTableModel) table.getModel();
                Object [] fila=new Object[3]; 
                fila[0]=list.get(i); // cantidad
                fila[1]=""; // 
                fila[2]=""; // 
                modelo.addRow(fila);
                //Sección 5
                table.setModel(modelo); 
            }
        }
        

    }
    
    private static void limpiarTabla() {
        DefaultTableModel model1 = (DefaultTableModel) table.getModel();
        model1.setRowCount(0);
    }
    
    // calculo de total = cant[0] * sueldo[1] / 26  ** en table
    private void calTotTbl (String dto){
        if(dto.equals("keyPress")){
            int position = table.getSelectedRow();
            double cant = Double.parseDouble(table.getValueAt(position, 0).toString());
            String val = table.getValueAt(position, 1).toString();
            if(!val.equals("")){
                double suel = Double.parseDouble(table.getValueAt(position, 1).toString());
                double aux = (double) Math.round(((cant*suel)/26) * 100d) / 100d; // solo 2 decimales   
                table.setValueAt(aux, position, 2); // pongo el valor    
            }else{
                table.setValueAt("", position, 2); // pongo el valor  
            }
        }else{
            int size = table.getRowCount();
            for (int i = 0; i < size; i++) {
                double cant = Double.parseDouble(table.getValueAt(i, 0).toString());
                String val = table.getValueAt(i, 1).toString();
                //System.out.println("aaa "+val);
                if(!val.equals("")){
                    double suel = Double.parseDouble(table.getValueAt(i, 1).toString());
                    double aux = (double) Math.round(((cant*suel)/26) * 100d) / 100d; // solo 2 decimales
                    table.setValueAt(aux, i, 2); // pongo el valor 
                }else{
                    table.setValueAt("", i, 2); // pongo el valor 
                }
            }
        }
    }

    // click btn calcular sub Tot 1
    private void calSubTot1() {
        String valTblTot = table.getValueAt(0, 2).toString();
        //System.out.println("calSubT 1  "+valTblTot);
        if(!valTblTot.equals("")){
            int size = table.getRowCount();
            //System.out.println("calSubT size  "+size);
            double acum = 0;
            for(int i=0; i<size; ++i){
                String valTbl = table.getValueAt(i, 2).toString();
                //System.out.println("calSubT for  "+valTbl);
                if(!valTbl.equals("")){
                    double tot = Double.parseDouble(valTbl);
                    acum += tot; 
                }
            }
            acum = (double) Math.round((acum) * 100d) / 100d; // solo 2 decimales   
            jTextField2.setText(String.valueOf(acum)); // en txtField SubTot 1   
        }
    }
    
}
