/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistaPanelApusDialog;

import controlador.manoObraController;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import modelo.ManoObra;
import vistaPanelApus.panelApus;
import static vistaPanelApus.panelApus.activoDlgManoObra;

/**
 *
 * @author personal1
 */
public class dialogManoObra extends javax.swing.JInternalFrame {

    /**
     * Creates new form dialogEquipo
     */
    
     // instancias
    manoObraController ctrManObra = new manoObraController();
    ManoObra datos = null;
    
     // variable para caracter
    private Character kpress;
    
    public dialogManoObra() {
        initComponents();
        setTitle("Consulta de datos de Mano de Obra");
        
        // Default
        setEsquemaTable();
        setTableEquipoAll();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        btnClosed = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Descripción: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 17, 90, -1));

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripción", "Sueldo", "Diario", "Hora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(1).setPreferredWidth(240);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 470, 160));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 12, 280, -1));

        btnClosed.setText("X");
        btnClosed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClosedActionPerformed(evt);
            }
        });
        jPanel1.add(btnClosed, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 13, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Total de registros");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClosedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClosedActionPerformed
        this.dispose();
        panelApus.activoDlgManoObra = false;
    }//GEN-LAST:event_btnClosedActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        int fila = table.rowAtPoint(evt.getPoint());
        panelApus.jTextField4.setText(table.getValueAt(fila, 0).toString());
        //frmIntFactura.txtCliente.setText(table.getValueAt(fila, 1).toString() + " "+ 
          //      table.getValueAt(fila, 2).toString());  
    }//GEN-LAST:event_tableMouseClicked

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
         kpress = evt.getKeyChar();
        if (kpress == KeyEvent.VK_ENTER) {
            getFiltoByCodAndDescrip();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dialogManoObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dialogManoObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dialogManoObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dialogManoObra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dialogManoObra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClosed;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    // no move columnTable y hide 
    private void setEsquemaTable() {
        // table
        table.getTableHeader().setReorderingAllowed(false);
    }

    // metodo para limpiar tabla
    private void clearTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
    }

    // metodo para traer todos los datos de equipo
    private void setTableEquipoAll() {
        // jTable1
        int sizeRows = table.getRowCount();
        if (sizeRows > 0) {
            clearTable();
        }
        List<ManoObra> list = ctrManObra.getManoObraoAll();

        if (list.isEmpty()) {
            // jLabel1
            jLabel1.setText("No hay registros");
        } else {
            jLabel1.setText("Total de registros: " + list.size());
        }

        addRowTable(list);
    }
    
     // lleno el cuerpo de la tabla
    private void addRowTable(List<ManoObra> list) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        Object[] row;
        for (ManoObra mano : list) {
            row = new Object[5];
            row[0] = mano.getId();
            row[1] = mano.getDescripcion();
            row[2] = mano.getSueldo();
            row[3] = mano.getDiario();
            row[4] = mano.getHora();
            
            model.addRow(row);
            row = null;
        }
        table.setModel(model);
    }

     // metodo para filtar
    private void getFiltoByCodAndDescrip() {
        // jTextField1 == la caja de busqueda
        // jRadioButton1 = codigo :::: jRadioButton2 = descripcion
        String fill = jTextField1.getText().trim();
        if (!fill.equals("")) {
            List<ManoObra> listFill = null;
            // codigo
           // if (jRadioButton1.isSelected()) {
             //   int id = vali.soloNumero(fill);
               // listFill = ctrEquip.getEquipoByID(id);
            //} else if (jRadioButton2.isSelected()) {
                // descripcion
                listFill = ctrManObra.getManoObraByDescripcion(fill);
            //}

            int sizeRows = table.getRowCount();
            if (sizeRows > 0) {
                clearTable();
            }

            if (listFill.isEmpty()) {
                // jLabel1
                jLabel1.setText("No se encontrarón resultados");
                clearTable();
            } else {

                addRowTable(listFill);
                jLabel1.setText("Total de registros: " + listFill.size());
            }
            listFill.clear();
        }
    }

    
}
