/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.manoObraController;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.ManoObra;
import util.validaciones;

/**
 *
 * @author personal
 */
public class FrmMano_obra extends javax.swing.JInternalFrame {

    /**
     * Creates new form mano_obra
     */
    // instancias
    manoObraController ctrManObra = new manoObraController();
    ManoObra datos = null;
    private validaciones vali = new validaciones();
    
    // variable para caracter
    private Character kpress;

    public FrmMano_obra() {
        initComponents();
        // color de fondo
        //getContentPane().setBackground(new java.awt.Color(237,179,88));

        setIconifiable(true);
        setTitle("Mano de Obra");
        
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        // no move colum table
        setEsquemaTable();
        setTableManObraAll();
        // default
        getIdSgt();
        rbCod.setSelected(true);
        btnEditar.setEnabled(false);

        txtCod.setEditable(false);
        txtDescrip.setLineWrap(true);
        txtDescrip.setWrapStyleWord(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCod = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescrip = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        txtSueldo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFsr = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtHora = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtCPC = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtNP = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtVae = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        btnTodos = new javax.swing.JButton();
        rbCod = new javax.swing.JRadioButton();
        rbDescrip = new javax.swing.JRadioButton();
        lblTot = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), " Gestión  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Código:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Descripción:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));
        jPanel1.add(txtCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 190, -1));

        txtDescrip.setColumns(20);
        txtDescrip.setRows(5);
        jScrollPane1.setViewportView(txtDescrip);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 190, 60));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Sueldo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        txtSueldo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSueldoKeyTyped(evt);
            }
        });
        jPanel1.add(txtSueldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 190, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("FSR:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        txtFsr.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFsrKeyTyped(evt);
            }
        });
        jPanel1.add(txtFsr, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 190, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Diario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 190, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Horario:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, -1, -1));

        txtHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHoraKeyTyped(evt);
            }
        });
        jPanel1.add(txtHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 190, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("CPC:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        txtCPC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPCActionPerformed(evt);
            }
        });
        jPanel1.add(txtCPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 190, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("NP/ND/EP:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));
        jPanel1.add(txtNP, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 190, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("VAE:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));
        jPanel1.add(txtVae, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 190, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, -1, -1));

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        jPanel1.add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        jButton1.setText("Nuevo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 300, 380));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "  Consulta / Registros  ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Descripción", "Sueldo", "FSR", "Diario", "Hora", "CPC", "NP/ND/EP", "VAE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setMinWidth(50);
            table.getColumnModel().getColumn(0).setPreferredWidth(50);
            table.getColumnModel().getColumn(0).setMaxWidth(50);
            table.getColumnModel().getColumn(1).setMinWidth(210);
            table.getColumnModel().getColumn(1).setPreferredWidth(210);
            table.getColumnModel().getColumn(1).setMaxWidth(210);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 700, 260));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Filtro:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });
        jPanel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 280, -1));

        btnTodos.setText("Todos");
        btnTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTodosActionPerformed(evt);
            }
        });
        jPanel2.add(btnTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, -1, -1));

        buttonGroup1.add(rbCod);
        rbCod.setText("Código");
        rbCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbCodActionPerformed(evt);
            }
        });
        jPanel2.add(rbCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        buttonGroup1.add(rbDescrip);
        rbDescrip.setText("Descripción");
        jPanel2.add(rbDescrip, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        lblTot.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTot.setText("Total de Registros: ");
        jPanel2.add(lblTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, 240, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 720, 380));

        btnClose.setText("X");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 0, -1, 40));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ingehisa.png"))); // NOI18N
        jLabel12.setText("INGEHISA / Mano de Obra");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCPCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPCActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // btn grabar
        setSaveManObra();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void rbCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbCodActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        this.dispose();
        home.activoManoObra = false;
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // btn editar
        setEditManObra();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
         // filtro por codigo y descripcion
        kpress = evt.getKeyChar();
        if (kpress == KeyEvent.VK_ENTER) {
            getFiltoByCodAndDescrip();
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void txtSueldoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSueldoKeyTyped
        vali.soloNumeroEvent(evt);
    }//GEN-LAST:event_txtSueldoKeyTyped

    private void txtFsrKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFsrKeyTyped
        vali.soloNumeroEvent(evt);
    }//GEN-LAST:event_txtFsrKeyTyped

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        vali.soloNumeroEvent(evt);
    }//GEN-LAST:event_jTextField1KeyTyped

    private void txtHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHoraKeyTyped
        vali.soloNumeroEvent(evt);
    }//GEN-LAST:event_txtHoraKeyTyped

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // btnGuardar  ::: 
        // txtDescrip, txtSueldo, txtFsr, jTextField1, txtHora, 
        // txtCPC, txtNP, txtVae, txtCod
        btnGuardar.setEnabled(false);
        btnEditar.setEnabled(true);
        int fila = table.rowAtPoint(evt.getPoint());
        txtCod.setText(table.getValueAt(fila, 0).toString());
        txtDescrip.setText(table.getValueAt(fila, 1).toString());
        txtSueldo.setText(table.getValueAt(fila, 2).toString());
        txtFsr.setText(table.getValueAt(fila, 3).toString());
        jTextField1.setText(table.getValueAt(fila, 4).toString());
        txtHora.setText(table.getValueAt(fila, 5).toString());
        txtCPC.setText(table.getValueAt(fila, 6).toString());
        txtNP.setText(table.getValueAt(fila, 7).toString());
        txtVae.setText(table.getValueAt(fila, 8).toString());
        
    }//GEN-LAST:event_tableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        btnEditar.setEnabled(false);
        btnGuardar.setEnabled(true);
        getIdSgt();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTodosActionPerformed
        setTableManObraAll();
    }//GEN-LAST:event_btnTodosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMano_obra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMano_obra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMano_obra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMano_obra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMano_obra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnTodos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblTot;
    private javax.swing.JRadioButton rbCod;
    private javax.swing.JRadioButton rbDescrip;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtCPC;
    private javax.swing.JTextField txtCod;
    private javax.swing.JTextArea txtDescrip;
    private javax.swing.JTextField txtFsr;
    private javax.swing.JTextField txtHora;
    private javax.swing.JTextField txtNP;
    private javax.swing.JTextField txtSueldo;
    private javax.swing.JTextField txtVae;
    // End of variables declaration//GEN-END:variables

    // no move columnTable y hide 
    private void setEsquemaTable() {
        // table
        table.getTableHeader().setReorderingAllowed(false);
    }

    // metodo para limpiar tabla
    private void clearTable() {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setRowCount(0);
    }

    // datos de carga default de la tabla Equipo
    private void setTableManObraAll() {
        // jTable1
        int sizeRows = table.getRowCount();
        if (sizeRows > 0) {
            clearTable();
        }
        List<ManoObra> listEq = ctrManObra.getManoObraoAll();

        if (listEq.isEmpty()) {
            // lblTot
            lblTot.setText("No hay registros");
        } else {
            lblTot.setText("Total de registros: " + listEq.size());
        }
        addRowTable(listEq);
    }

    // lleno el cuerpo de la tabla
    private void addRowTable(List<ManoObra> listEq) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        Object[] row;
        for (ManoObra mano : listEq) {
            row = new Object[9];
            row[0] = mano.getId();
            row[1] = mano.getDescripcion();
            row[2] = mano.getSueldo();
            row[3] = mano.getFsr();
            row[4] = mano.getDiario();
            row[5] = mano.getHora();
            row[6] = mano.getCpc();
            row[7] = mano.getNp_nd_ep();
            row[8] = mano.getVae();

            model.addRow(row);
            row = null;
        }
        table.setModel(model);
    }

    //metodo que trae el idSgt
    private void getIdSgt() {
        // txtCod
        int idSgt = ctrManObra.getIDSgt();
        txtCod.setText("" + idSgt);
    }
    
     // metodo para guardar mano de obra nuevo
    private void setSaveManObra() {
        // txtDescrip, txtSueldo, txtFsr, jTextField1, txtHora, 
        // txtCPC, txtNP, txtVae
        if (txtDescrip.getText().length() > 0
                && txtSueldo.getText().length() > 0
                && txtFsr.getText().length() > 0
                && jTextField1.getText().length() > 0
                && txtHora.getText().length() > 0) {
            try {
                datos = new ManoObra();
                datos.setDescripcion(txtDescrip.getText());
                datos.setSueldo(Double.parseDouble(txtSueldo.getText()));
                datos.setFsr(Double.parseDouble(txtFsr.getText()));
                datos.setDiario(Double.parseDouble(jTextField1.getText()));
                datos.setHora(Double.parseDouble(txtHora.getText()));
                datos.setCpc(txtCPC.getText());
                datos.setNp_nd_ep(txtNP.getText());
                datos.setVae(txtVae.getText());

                if (ctrManObra.ingresar(datos)) {
                    JOptionPane.showConfirmDialog(this, "Registro grabado con exito", "Confirmación", 2);
                    setTableManObraAll();
                } else {
                    JOptionPane.showConfirmDialog(this, "Error server", "Error", 2);
                }
                datos = null;
            } catch (Exception e) {
                System.out.println("err-saveEq " + e.getMessage());
                e.getMessage();
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Campos vacios", "Alerta", 2);
        }
    }
    
    // metodo para actualizar registro de mano de obra
     private void setEditManObra() {
        // txtDescrip, txtSueldo, txtFsr, jTextField1, txtHora, 
        // txtCPC, txtNP, txtVae, txtCod
        if (txtDescrip.getText().length() > 0
                && txtSueldo.getText().length() > 0
                && txtFsr.getText().length() > 0
                && jTextField1.getText().length() > 0
                && txtHora.getText().length() > 0) {
            try {
                datos = new ManoObra();
                datos.setDescripcion(txtDescrip.getText());
                datos.setSueldo(Double.parseDouble(txtSueldo.getText()));
                datos.setFsr(Double.parseDouble(txtFsr.getText()));
                datos.setDiario(Double.parseDouble(jTextField1.getText()));
                datos.setHora(Double.parseDouble(txtHora.getText()));
                datos.setCpc(txtCPC.getText());
                datos.setNp_nd_ep(txtNP.getText());
                datos.setVae(txtVae.getText());
                datos.setId(Integer.parseInt(txtCod.getText()));

                if (ctrManObra.actualizar(datos)) {
                    JOptionPane.showConfirmDialog(this, "Registro actualizado con exito", "Confirmación", 2);
                    setTableManObraAll();
                } else {
                    JOptionPane.showConfirmDialog(this, "Error server", "Error", 2);
                }
                datos = null;
            } catch (Exception e) {
                System.out.println("err-saveEq " + e.getMessage());
                e.getMessage();
            }
        } else {
            JOptionPane.showConfirmDialog(this, "Campos vacios", "Alerta", 2);
        }
    }
    
     // metodo para filtar
     private void getFiltoByCodAndDescrip() {
        // jTextField2 == la caja de busqueda
        // rbCod = codigo :::: rbDescrip = descripcion
        String fill = jTextField2.getText().trim();
        if (!fill.equals("")) {
            List<ManoObra> listFill = null;
            // codigo
            if (rbCod.isSelected()) {
                int id = vali.soloNumero(fill);
                listFill = ctrManObra.getManoObraByID(id);
            } else if (rbDescrip.isSelected()) {
                // descripcion
                listFill = ctrManObra.getManoObraByDescripcion(fill);
            }

            int sizeRows = table.getRowCount();
            if (sizeRows > 0) {
                clearTable();
            }

            if (listFill.isEmpty()) {
                // lblTot
                lblTot.setText("No se encontrarón resultados");
                clearTable();
            } else {

                addRowTable(listFill);
                lblTot.setText("Total de registros: " + listFill.size());
            }
            listFill.clear();
        }
    }
}
