/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ofertController;
import controlador.usuarioController;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import modelo.Oferta;
import modelo.Usuarios;
import sun.swing.table.DefaultTableCellHeaderRenderer;

/**
 *
 * @author personal
 */
public class FrmOferta extends javax.swing.JInternalFrame {

    /**
     * Creates new form oferta
     */
    usuarioController ctrUser = null;

    private ofertController ctrOfert = new ofertController();

    public FrmOferta() {
        initComponents();
        setTitle("Ofertas");

        // default componentes
        setTablesNoMoveHeader();
        llenarResponsable();
        setLlenarDatosTbl() ;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("x");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, 49, -1));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/ingehisa.png"))); // NOI18N
        jLabel1.setText("INGEHISA / Oferta");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 220, 40));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 70, 190, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Oferta", "Empresa", "Descripcion", "Ubicacion", "Responsable", "Elaborado por", "Fecha", "Subtotal", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 850, 273));

        jButton1.setText("Actualizar ");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 380, -1, -1));

        jButton2.setText("Guardar");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Responsable");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Fecha Fin");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Fecha Inicio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jTextField1.setText("YY / MM / DD");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        jTextField2.setText("YY / MM / DD");
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 140, -1));

        jButton4.setText("Filtrar");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 70, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        home.activoOferta = false;
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmOferta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmOferta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

    // hacer que cabecera se quede fija y columnas alineadas a la derecha
    private void setTablesNoMoveHeader() {
        jTable1.getTableHeader().setReorderingAllowed(false);
        /*
        DefaultTableCellRenderer cellRenderer = new DefaultTableCellHeaderRenderer();
        cellRenderer.setHorizontalAlignment(JLabel.RIGHT);
        // table 2 al 5
        for (int i = 2; i < 6; ++i) {
            jTable1.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
            jTable1.getColumnModel().getColumn(i).setCellRenderer(cellRenderer);
        }*/
    }

    private void llenarResponsable() {
        // jComboBox1
        ctrUser = new usuarioController();
        List<Usuarios> users = (ArrayList<Usuarios>) ctrUser.getUsuariosAllByResponsable();
        DefaultComboBoxModel cboModel = new DefaultComboBoxModel();
        for (Usuarios item : users) {
            cboModel.addElement(item);
        }
        jComboBox1.setModel(cboModel);
    }

    private void limpiarTabla() {
        DefaultTableModel model1 = (DefaultTableModel) jTable1.getModel();
        model1.setRowCount(0);
    }

    // cargamos los datos OFERTA
    private void setLlenarDatosTbl() {
        if (jTable1.getRowCount() > 0) {
            limpiarTabla();
        }

        DefaultTableModel modelo = (DefaultTableModel) jTable1.getModel();

        List<Oferta> listOfrtPA = ctrOfert.getOfertByPresuApus();
        List<Oferta> listOfrtPM = ctrOfert.getOfertByPresuManual();

        for (Oferta oferta : listOfrtPA) {
            //Sección 2
            Object[] fila = new Object[9];
            //Sección 3
            fila[0] = oferta.getId();
            fila[1] = oferta.getOferta();
            fila[2] = oferta.getDescripcion();
            fila[3] = oferta.getUbicacion();
            fila[4] = oferta.getResponsable();
            fila[5] = oferta.getElab_por();
            fila[6] = oferta.getFecha();
            fila[7] = oferta.getSubtotal();
            fila[8] = oferta.getTelefono();

            //Sección 4
            modelo.addRow(fila);
        }
        //Sección 5
        jTable1.setModel(modelo);

        // add la otra lista
        for (Oferta oferta : listOfrtPM) {
            //Sección 2
            Object[] fila = new Object[9];
            //Sección 3
            fila[0] = oferta.getId();
            fila[1] = oferta.getOferta();
            fila[2] = oferta.getDescripcion();
            fila[3] = oferta.getUbicacion();
            fila[4] = oferta.getResponsable();
            fila[5] = oferta.getElab_por();
            fila[6] = oferta.getFecha();
            fila[7] = oferta.getSubtotal();
            fila[8] = oferta.getTelefono();

            //Sección 4
            modelo.addRow(fila);
        }
        //Sección 5
        jTable1.setModel(modelo);
    }
}


/*
para los apus presupuesto 
select id, empresa, oferta, fecha_creacion, id_apus from presupuesto where id_apus !=0
group by id_apus , id
order by id_apus asc

para los manuales
select id, empresa, oferta, fecha_creacion, id_manual from presupuesto where id_manual !=0
group by id_manual , id
order by id_manual asc

OFERRTA 1
AGRUPAR SEGUN VERSIONES
SI NO ES EL CASO SOLO VA LA TABLA PRINCIPAL


ESTE FRM VA LLENAR TODAS LAS OFERTAS QUE SE HAGAN DE MANERA MANUAL (EL MENU MANUAL)

OFERTA LLENO CON OFERTA DE LA BASE DE DATOS
ELABORADO CBO CON OPCIONES DE MILTON, JUSTO ......

LO DEMAS ES MANUAL OSEA TIPIADO

TRAER TODO LAS OFERTAS SEGUN ESTEN EL ORDEN DE TBL PRINCIPAL Y SI TIENE VERSIONES SE COLOCAN DE BAJO DE LA MISMA

 */
